version: '3'

services:

  postgres:
    container_name: postgres
    image: postgres:12.3
    volumes:
      - ./postgres/docker-entrypoint-initdb:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  discovery-service:
    build: ../discovery-service
    ports:
      - 8761:8761
    expose:
    - "8761"

  gateway:
    build: ../gateway
    ports:
      - 80:80
    links:
      - discovery-service
    depends_on:
      - discovery-service
    environment:
      - SERVER_PORT=80
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka

  player-service:
    build: ../player-service
    ports:
      - 8050:8050
    links:
      - discovery-service
    depends_on:
      - discovery-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://service-discovery:8761
      - DB_HOST=postgres

  commission-service:
    build: ../commission-service
    ports:
      - 8150:8150
    links:
      - discovery-service
    depends_on:
      - discovery-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://service-discovery:8761
      - DB_HOST=postgres

volumes:
  pg-data: