version: '3'

services:

  postgres:
    container_name: postgres
    image: postgres:12.3
    volumes:
      - ./postgres/docker-entrypoint-initdb:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  pg-data:
