spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
        jdbc:
          lob:
            non_contextual_creation: true
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://${db_host}:5432/player
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

db_host: localhost