spring:
  application:
    name: commission-service

  flyway:
    table: schema_history
    out-of-order: true
    locations: classpath:db/player/migration

server:
  port: 8150

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
